debug: true

# This could be set higher for less updates / second.
updateInterval: 20 # (Ticks)

# Entity Update frequency in Milliseconds.
entityUpdateSpeed: 250
# Delay before the events will start (in Milliseconds).
handleListenDelay: 5000

# At what range in blocks the Skeletons will use a sword.
skeletonSwordSwitch: # Skeletons will use a wooden sword.
  enabled: true
  swordRange: 5

# At what range in blocks the Wither Skeletons will use a sword.
witherSkeletonSwordSwitch: # Wither Skeletons will use a bow with the flame enchantment.
  enabled: true
  swordRange: 8

# Makes Creepers spawn more regularly with effects.
creeperSpawnPotionEffect:
  enabled: true
  effectDuration: 60 # Duration of the given effect.
  spawnChance: 20 # 1 in 20 Creepers spawns with an effect. (note: larger number is a smaller chance)
  positiveEffects: true
  # Includes: ABSORPTION, RESISTANCE, INVISIBILITY, JUMP BOOST, WATER BREATHING, REGENERATION, SPEED, STRENGTH, FIRE RESISTANCE, HASTE
  negativeEffects: true
  # Includes: POISON, WITHER, BLINDNESS, MINING FATIQUE, WEAKNESS, HUNGER, NAUSEA
  rareEffects: true
  # Includes: LEVITATION, DOLPHINS GRACE, GLOWING, LUCK, BAD OMEN, SATURATION

# Whether Witches can spawn Baby Zombies at night to help it fight the player.
witchNecromancer: # Summoned Baby Zombies won't drop Anything.
  enabled: true
  cooldown: 30 # How many Seconds to wait before summoning again.
  spawnAmount: 3 # The maximum amount of Zombies that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  spawnRadius: 3 # How many blocks away from the Witch the Baby Zombies can spawn.
  scanRadius: 16 # The distance from the player that will be checked for Witches.

# Whether the Wither can spawn Wither Skeletons to help him in battle.
witherReinforcements: # Summoned Wither Skeletons won't drop Anything
  enabled: true
  cooldown: 45 # How many Seconds to wait before summoning again.
  spawnRadius: 10 # Maximum amount of blocks that Wither Skeletons can spawn from the Wither.
  spawnChance: 10 # 1/100 Procental Chance that reinforcements will spawn if the Wither is attacked. (note: larger number is a smaller chance)
  spawnAmount: 2 # Maximum amount of Wither Skeletons that will spawn at each interval. (note: Spawn amounts will differ due to RNG).

# Whether the Wither can give negative effects to players around it.
witherEffects: # Includes: BLINDNESS, NAUSEA, HUNGER, MINING FATIQUE, WEAKNESS
  enabled: true
  cooldown: 40 # How many Seconds to wait before releasing effects again.
  spawnChance: 10 # The chance the effects will happen if the Wither is attacked.
  attackRadius: 8 # Maximum radius of the attack.
  attackDuration: 10 # Duration of the given potion effect.

# Whether the Ender Dragon will rest on The End Portal.
NoDragonPerching:
  enabled: true

# Whether The Ender Dragon spawns Baby Ender Dragons to kill the player.
babyEnderDragons:
  enabled: true
  spawnRadius: 15 # Maximum amount of blocks that Baby Ender Dragons can spawn from The Ender Dragon.
  spawnChance: 10 # 1/100 Procental Chance that the Baby Ender Dragon spawn will occur. (note: larger number is a smaller chance)
  spawnAmount: 2 # Maximum amount of Baby Ender Dragons that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  damageBooster: 2 # Amount of damage that the Baby Ender Dragons will do.
  dragonRegen: true # Whether The Ender Dragon will regenerate health if a Baby Ender Dragon hits a player.

# Whether The Ender Dragon spawns Endermites to kill the player.
enderDragonMites:
  enabled: true
  spawnRadius: 15 # Max distance from the portal where the endermite could spawn.
  spawnChance: 10 # 1/100 Procental Chance that the Endermite spawn will occur. (note: larger number is a smaller chance)
  spawnAmount: 2 # Maximum amount of Endermite that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  damageBooster: 2 # Amount of damage that the Endermite will do.
  dragonRegen: true # Whether The Ender Dragon will regenerate health if an Endermite hits a player.
  
# Whether the enderdragon uses his rain ability or not
enderDragonRain:
  enabled: true
  attackChance: 20  # 1/100 Procental Chance that the Rain will occur. (note: larger number is a smaller chance)
  attackStrength: 10 # Maximum amount of fireballs that will spawn at each interval. (note: Spawn amounts will differ due to RNG).
  attackSpeed: 40 # How many ticks to wait before releasing another fireball on the player.
  attackRange: 100 # Max distance from the portal where the fireballs could spawn.
  attackWarning: true # Whether the players will see a visible warning before the attack.