# Generated for BetterMobs version @version@

# This could be set higher for fewer updates / second.
# The update interval are used for changing entities and casting their abilities.
updateInterval: 20 # (Ticks)

# You can comment the materials if they're not available.
meleeWeapons:
  - minecraft:wooden_sword
  - minecraft:stone_sword
  - minecraft:iron_sword
  - minecraft:golden_sword
  - minecraft:diamond_sword
  - minecraft:netherite_sword
  - minecraft:wooden_axe
  - minecraft:stone_axe
  - minecraft:iron_axe
  - minecraft:golden_axe
  - minecraft:diamond_axe
  - minecraft:netherite_axe

rangedWeapons:
  - minecraft:bow
  - minecraft:crossbow

# Check online if there are updates available.
checkUpdates: true

# Enabling this will induce a lot of spam in the console.
debug: false

# Please don't change the version of the config unless you know what you're doing.
version: 1