name: BetterMobs
main: vepnar.bettermobs.Main
version: @version@
author: Vepnar
api-version: 1.13
load: POSTWORLD
commands:
  bettermobs:
    aliases: bm
    description: Access bettermob plugin settings.
permissions:
  bettermobs.features.reload:
    description: allows the the user to reload config files.
    default: op
  bettermobs.features.show:
    description: allows the user look into the status of features.
    default: op
  bettermobs.features.enable:
    description: allows the the user to enable features.
    default: op
  bettermobs.features.disable:
    description: allows the the user to disable features.
    default: op
  bettermobs.messages.outdated:
    description: Allow a user to get notified when the plugin is outdated.
    default: op
