name: BetterMobs
main: vepnar.bettermobs.Main
version: @version@
author: Vepnar
api-version: 1.13
load: POSTWORLD
commands:
  bettermobs:
    aliases: bm
    description: Access bettermob plugin settings
permissions:
  bettermobs.reload:
    description: allows the the user to reload the config file
    default: op
  bettermobs.author:
    description: Allow the user to show the author of the better mobs plugin.
    default: true