name: BetterMobs
main: vepnar.bettermobs.Main
version: @version@
author: Vepnar
api-version: 1.13
load: POSTWORLD
commands:
  bettermobs:
    aliases: bm
    description: Access bettermob plugin settings.
permissions:
  bettermobs.features.reload:
    description: Allow the player to reload the config files & features.
    default: op
  bettermobs.features.show:
    description: Allow the player to see the status of all features.
    default: op
  bettermobs.features.enable:
    description: Allow the player to user to enable features.
    default: op
  bettermobs.features.disable:
    description: Allow the player to user to disable features.
    default: op
  bettermobs.messages.outdated:
    description: Allow the player to get notified when the plugin is outdated.
    default: op
